# FADDL Match - Monorepo Netlify Configuration
# Optimized for workspace dependency resolution
[build]
  base = "."
  command = "chmod +x netlify-emergency-build.sh && ./netlify-emergency-build.sh"
  functions = "netlify/functions" 
  publish = "apps/web/.next"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PUBLIC_APP_URL = "https://faddlmatch.com"
  NODE_ENV = "production"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NETLIFY_USE_YARN = "false"
  # Monorepo optimization flags
  NPM_CONFIG_WORKSPACE_INSTALL = "true"
  NPM_CONFIG_INCLUDE_WORKSPACE_ROOT = "true"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  # Build optimization
  NETLIFY_SKIP_YARN_INSTALL = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # STRIPE environment variables configured in Netlify dashboard

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Static assets caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Basic redirects
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/login"
  to = "/auth/login" 
  status = 301

[[redirects]]
  from = "/signup"
  to = "/auth/signup"
  status = 301

# API proxy
[[redirects]]
  from = "/api/functions/*"
  to = "https://dvydbgjoagrzgpqdhqoq.supabase.co/functions/v1/:splat"
  status = 200
  force = true

# Dev settings
[dev]
  command = "npm run dev"
  port = 3000