# FADDL Match - Netlify Configuration
[build]
  command = "cd apps/web && npm install && npm run build"
  functions = "netlify/functions"
  publish = "apps/web/.next"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Static assets caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Basic redirects
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/login"
  to = "/auth/login" 
  status = 301

[[redirects]]
  from = "/signup"
  to = "/auth/signup"
  status = 301

# API proxy
[[redirects]]
  from = "/api/functions/*"
  to = "https://dvydbgjoagrzgpqdhqoq.supabase.co/functions/v1/:splat"
  status = 200
  force = true

# Dev settings
[dev]
  command = "cd apps/web && npm run dev"
  port = 3000